* GenMutator
[Onging work]

A Java mutator. Not for mutation testing.



** Build and Usage
+ Requirements: [[https://spoon.gforge.inria.fr/index.html][Spoon]] used in this tool requires Java 11 or newer versions.
  
+ Build a jar with dependencies as below.
#+begin_src sh
mvn compile assembly:single
#+end_src

+ Use it with input directory (=-i=) and output directory (=-o=) specified.
+ =-n= is optional, default to 1. Set it to other values for multiple cycles of generation.
#+begin_src sh
java -jar target/genMutator-1.0-SNAPSHOT-jar-with-dependencies.jar -i type1-proj  -o .output/type1 -n 5
#+end_src

Or check the =examples= directory.
#+begin_src sh
cd examples
./run-example.sh
#+end_src

*** Configuration

** Mutators
+ =AddIfMutator= adds a =if= structure surrounding function invocations with a probability (preset 40%). 
+ =BinOpExprMutator= changes the binary operators (logic operators, comparison operators, arithmetic operators) used in the binary operation expression.
+ =VarRenameMutator= changes a variable to another name generated from a dictionary with a probability. 
+ =FnNameMutator= changes the names of methods (functions) within the source code.
+ =InvocationMutator= changes the names of the invoked methods to other method names.
+ =TypeRefMutator= selects type references, excluding primitive types, and mutates them by replacing them with other types. 


** Credits
+ Borrow some code from https://github.com/SpoonLabs/metamutator.
+ Words for name generation from https://github.com/dariusk/corpora and https://github.com/kohsuke/wordnet-random-name (from wordnet).
